// Action Management MVP — Mock Data & Constants
// All globals prefixed AM_ to avoid collisions

const AM_CATEGORIES = [
  { id:'safety',      name:'Health & Safety',       color:'#4CADAF', short:'Safety'      },
  { id:'env',         name:'Environmental',          color:'#1A94CE', short:'Env'         },
  { id:'reliability', name:'Reliability',            color:'#0976B8', short:'Reliability' },
  { id:'efficiency',  name:'Industrial Efficiency',  color:'#0E4E95', short:'Efficiency'  },
  { id:'quality',     name:'Quality & Process',      color:'#B41E53', short:'Quality'     },
  { id:'people',      name:'People Development',     color:'#D95527', short:'People'      },
  { id:'innovation',  name:'Innovation & Growth',    color:'#E46825', short:'Innovation'  },
  { id:'risk',        name:'Industrial Risk',        color:'#ECA122', short:'Risk'        },
  { id:'performance', name:'Performance',            color:'#7754AF', short:'Performance' },
];

const AM_STATUS_CFG = {
  'Open':        { color:'#3382C4', bg:'#EAF2FA', label:'OPEN'        },
  'In Progress': { color:'#E46825', bg:'#FFF3E0', label:'IN PROGRESS' },
  'On Hold':     { color:'#ECA122', bg:'#FFF8EC', label:'ON HOLD'     },
  'Completed':   { color:'#4CADAF', bg:'#E8F8F5', label:'COMPLETED'   },
  'Cancelled':   { color:'#888888', bg:'#F5F5F5', label:'CANCELLED'   },
  'Draft':       { color:'#999999', bg:'#F0F0F0', label:'DRAFT'       },
};

const AM_PRIORITY_CFG = {
  'Critical': { color:'#DE1D3F' },
  'High':     { color:'#D95527' },
  'Medium':   { color:'#ECA122' },
  'Low':      { color:'#3382C4' },
};

const AM_SOURCE_CFG = {
  'Manual':      { color:'#64748B', bg:'#F1F5F9' },
  'TAG+':        { color:'#6366F1', bg:'#EEF2FF' },
  'eCheck':      { color:'#0891B2', bg:'#ECFEFF' },
  'eEvent':      { color:'#E11D48', bg:'#FFF1F2' },
  'SMAT':        { color:'#D97706', bg:'#FFFBEB' },
  'EHS':         { color:'#DC2626', bg:'#FEF2F2' },
  'Kaizen':      { color:'#059669', bg:'#ECFDF5' },
  'Risk':        { color:'#EA580C', bg:'#FFF7ED' },
  'Audit':       { color:'#7C3AED', bg:'#F5F3FF' },
  'Digital PCS': { color:'#2563EB', bg:'#EFF6FF' },
  'Automatic':   { color:'#6B7280', bg:'#F9FAFB' },
};

const AM_USERS = [
  { id:'u1', name:'Jean Dupont',  initials:'JD', color:'#3382C4' },
  { id:'u2', name:'Marie Leroy', initials:'ML', color:'#4CADAF' },
  { id:'u3', name:'Sofia Ruiz',  initials:'SR', color:'#D95527' },
  { id:'u4', name:'Paul Lambert',initials:'PL', color:'#0976B8' },
  { id:'u5', name:'Nina Cheng',  initials:'NC', color:'#B41E53' },
  { id:'u6', name:'Ahmed Bali',  initials:'AB', color:'#ECA122' },
];

const AM_ACTIONS_INIT = [
  { id:'ACT-2026-00142', description:'Inspect conveyor belt seal on Line 4 — north-side roller showing abnormal wear pattern requiring immediate assessment',
    pillar:'reliability', status:'Open', subStatus:'In Progress', priority:'High', source:'Manual',
    assignee:'u1', due:'2026-05-30', created:'2026-05-10', overdue:false,
    structure:'Fabrication > Line 4 > Conveyor A', category:'Preventive Maintenance',
    planId:'AP-2026-001', sapWo:null, cmms:false,
    comments:[{ user:'u2', date:'2026-05-12', text:'Parts ordered, delivery expected May 28.' }],
    history:[{ date:'2026-05-10', action:'Action created by Jean Dupont' },{ date:'2026-05-11', action:'Status changed to In Progress' }] },
  { id:'ACT-2026-00141', description:'Update EHS risk register H2 2026 — reflect new chemical storage arrangements in zone C3. Legal compliance deadline.',
    pillar:'safety', status:'Open', subStatus:'On Hold', priority:'Critical', source:'EHS',
    assignee:'u2', due:'2026-05-15', created:'2026-05-01', overdue:true,
    structure:'EHS > Zone C3', category:'Compliance',
    planId:null, sapWo:'WO-48821', cmms:true,
    linkedRecord:{ type:'EHS', module:'Risk assessment', id:'RA-2026-0312', title:'Chemical storage reconfiguration — Zone C3',
      description:'Risk assessment opened after the relocation of class 3 flammable liquids into Zone C3. New adjacency to the oxidizer rack raises the storage incompatibility rating. Assessment flags that the risk register and SDS matrix must be revised to reflect the new layout before the next regulatory audit.',
      status:'Open', date:'2026-05-01', reporter:'u2' },
    comments:[],
    history:[{ date:'2026-05-01', action:'Created — linked from EHS module' },{ date:'2026-05-16', action:'Overdue — escalated to manager' }] },
  { id:'ACT-2026-00140', description:'Train 3 operators on 5S audit methodology before Q3 cycle begins — schedule slots with shift supervisor',
    pillar:'people', status:'In Progress', subStatus:'In Progress', priority:'Medium', source:'Manual',
    assignee:'u3', due:'2026-05-31', created:'2026-05-08', overdue:false,
    structure:'Operations > Workshop A', category:'Training',
    planId:'AP-2026-002', sapWo:null, cmms:false,
    comments:[{ user:'u3', date:'2026-05-20', text:'Two operators trained. Last session scheduled May 29.' }],
    history:[{ date:'2026-05-08', action:'Created by Sofia Ruiz' },{ date:'2026-05-15', action:'First training session completed' }] },
  { id:'ACT-2026-00139', description:'Replace air filter unit in Sector B — past service interval, procurement order raised, installation pending maintenance window',
    pillar:'env', status:'Open', subStatus:'In Progress', priority:'High', source:'TAG+',
    assignee:'u4', due:'2026-05-25', created:'2026-05-05', overdue:true,
    structure:'Fabrication > Sector B > Filter Station', category:'Corrective Maintenance',
    planId:null, sapWo:'WO-48790', cmms:true,
    linkedRecord:{ type:'TAG+', module:'Tag', id:'TAG-2156', title:'Sector B filter — differential pressure high',
      description:'Differential pressure across the Sector B air filter unit exceeded the 250 Pa alarm threshold during the automated round on 04/05. Logged reading of 318 Pa indicates filter media saturation and restricted airflow. Tag auto-generated and routed to maintenance for filter replacement.',
      status:'Open', date:'2026-05-04', reporter:'u4' },
    comments:[],
    history:[{ date:'2026-05-05', action:'Created from TAG+ anomaly TAG-2156' },{ date:'2026-05-06', action:'Linked to SAP WO-48790' }] },
  { id:'ACT-2026-00138', description:'Validate quality check procedure doc QCP-12B — reviewed and signed off by plant manager, upload to DMS',
    pillar:'quality', status:'Completed', subStatus:null, priority:'Low', source:'Audit',
    assignee:'u1', due:'2026-05-10', created:'2026-04-28', overdue:false,
    structure:'Quality > QC Lab', category:'Documentation',
    planId:'AP-2026-001', sapWo:null, cmms:false,
    linkedRecord:{ type:'Audit', module:'Audit finding', id:'AUD-2026-044', title:'QCP-12B revision not signed off',
      description:'Internal quality audit found that procedure QCP-12B had been revised but not formally validated or archived in the DMS. Finding rated minor non-conformity. Corrective action required: obtain plant manager sign-off and upload the controlled copy to the document management system.',
      status:'Closed', date:'2026-04-28', reporter:'u5' },
    comments:[{ user:'u1', date:'2026-05-10', text:'Document validated and uploaded to DMS.' }],
    history:[{ date:'2026-04-28', action:'Created from Audit finding' },{ date:'2026-05-10', action:'Completed by Jean Dupont' }] },
  { id:'ACT-2026-00137', description:'Calibrate pressure gauges on Unit 7 — quarterly calibration due for 4 pressure gauges with instrumentation team',
    pillar:'risk', status:'Open', subStatus:'In Progress', priority:'High', source:'SMAT',
    assignee:'u4', due:'2026-05-28', created:'2026-05-12', overdue:false,
    structure:'Production > Unit 7 > Instrumentation', category:'Preventive Maintenance',
    planId:null, sapWo:null, cmms:false,
    linkedRecord:{ type:'SMAT', module:'SMAT observation', id:'SMAT-0412', title:'Pressure gauges past calibration interval',
      description:'During the SMAT walkthrough on Unit 7, four pressure gauges on the instrumentation skid were observed carrying calibration tags last stamped in Q1. Quarterly calibration is overdue, creating a measurement-reliability risk for the process loop. Observation logged for instrumentation team follow-up.',
      status:'Open', date:'2026-05-12', reporter:'u2' },
    comments:[],
    history:[{ date:'2026-05-12', action:'Created from SMAT walkthrough' }] },
  { id:'ACT-2026-00136', description:'Conduct monthly SMAT walkthrough — 12 safety observations required per protocol for May cycle',
    pillar:'safety', status:'In Progress', subStatus:'In Progress', priority:'Medium', source:'SMAT',
    assignee:'u2', due:'2026-05-31', created:'2026-05-14', overdue:false,
    structure:'EHS > Production Floor', category:'Safety Observation',
    planId:null, sapWo:null, cmms:false,
    linkedRecord:{ type:'SMAT', module:'SMAT campaign', id:'SMAT-0398', title:'May safety management walkthrough cycle',
      description:'Monthly SMAT campaign requiring 12 documented safety observations across the production floor. Campaign tracks managers’ field presence and the quality of the safety dialogues held with operators. Each observation must record a behaviour, a discussion outcome and any corrective commitment.',
      status:'In Progress', date:'2026-05-14', reporter:'u2' },
    comments:[{ user:'u2', date:'2026-05-22', text:'7/12 observations completed.' }],
    history:[{ date:'2026-05-14', action:'Monthly SMAT cycle initiated' }] },
  { id:'ACT-2026-00135', description:'Implement 5S improvement in packaging zone per post-audit visual management standards',
    pillar:'performance', status:'Open', subStatus:'In Progress', priority:'Low', source:'Manual',
    assignee:'u3', due:'2026-06-15', created:'2026-05-18', overdue:false,
    structure:'Packaging > Zone P1', category:'Continuous Improvement',
    planId:'AP-2026-002', sapWo:null, cmms:false,
    comments:[],
    history:[{ date:'2026-05-18', action:'Created by Sofia Ruiz' }] },
  { id:'ACT-2026-00134', description:'Review and update emergency evacuation plan for Building C following latest facility changes',
    pillar:'safety', status:'Draft', subStatus:null, priority:'Medium', source:'Manual',
    assignee:'u5', due:'2026-06-01', created:'2026-05-24', overdue:false,
    structure:'EHS > Building C', category:'Emergency Preparedness',
    planId:null, sapWo:null, cmms:false, comments:[],
    history:[{ date:'2026-05-24', action:'Draft created by Nina Cheng' }] },
  { id:'ACT-2026-00133', description:'Install additional safety lighting in Corridor 3B — identified during night shift inspection report',
    pillar:'safety', status:'Cancelled', subStatus:null, priority:'Low', source:'eEvent',
    assignee:'u6', due:'2026-05-20', created:'2026-05-02', overdue:false,
    structure:'Facilities > Corridor 3B', category:'Corrective Action',
    planId:null, sapWo:null, cmms:false,
    linkedRecord:{ type:'eEvent', module:'Event report', id:'EVT-0231', title:'Low lighting reported — Corridor 3B night shift',
      description:'Night shift operator reported poor visibility in Corridor 3B during the 02:00 round, citing a darkened section between access doors. Logged as a minor hazard observation with no injury. Suggested mitigation was supplementary safety lighting along the corridor run.',
      status:'Closed', date:'2026-05-02', reporter:'u6' },
    comments:[],
    history:[{ date:'2026-05-02', action:'Created from event report' },{ date:'2026-05-19', action:'Cancelled — resolved by facilities team' }] },
];

const AM_PLANS_INIT = [
  { id:'AP-2026-001', title:'Q2 Equipment Reliability Improvement', status:'Deployed',
    description:'Comprehensive plan to address conveyor and pressurization equipment reliability across Line 4 and Unit 7.',
    owner:'u4', start:'2026-04-01', end:'2026-06-30',
    goals:'Reduce unplanned downtime by 15% across targeted lines.',
    monitoring:'Weekly review during Reliability pillar ritual.',
    easeCost:'Moderate — 3 work orders + parts procurement.',
    watchlist:['u1','u2'], actionIds:['ACT-2026-00142','ACT-2026-00138'], done:1, total:2, module:'TAG+',
    linkedRecord:{ type:'TAG+', id:'TAG-1842',
      title:'Line 4 conveyor system — reliability audit Q1 findings',
      description:'Reliability audit of Line 4 in Q1 2026 flagged abnormal wear on three conveyor roller assemblies and evidence of pressurisation issues on the north-side seal. Risk of unplanned stoppage rated medium-high by the auditor. An action plan was requested by the Reliability pillar owner to close all findings before the Q3 production ramp.',
      status:'Open', date:'2026-03-28', reporter:'u4' } },
  { id:'AP-2026-002', title:'5S Culture Rollout — Packaging & Operations', status:'Deployed',
    description:'Structured 5S implementation across packaging and operations departments.',
    owner:'u3', start:'2026-05-01', end:'2026-07-31',
    goals:'Achieve 5S certification for 3 departments by end of Q3.',
    monitoring:'Monthly 5S audit score tracked in Performance pillar.',
    easeCost:'Low — primarily time investment.',
    watchlist:['u1','u4'], actionIds:['ACT-2026-00140','ACT-2026-00135'], done:0, total:2, module:'Kaizen',
    linkedRecord:{ type:'Kaizen', id:'KZN-2026-007',
      title:'5S assessment — Packaging & Operations departments',
      description:'Post-Kaizen event assessment of Packaging and Operations identified significant gaps in visual management standards, material storage organisation, and floor-marking compliance. Both departments scored below the 3/5 certification threshold. The Kaizen team recommended a structured cultural rollout as a corrective action before the Q3 2026 audit cycle.',
      status:'Closed', date:'2026-04-20', reporter:'u3' } },
  { id:'AP-2026-003', title:'EHS Compliance Sprint H2', status:'Draft',
    description:'Preparation and compliance actions for H2 regulatory requirements.',
    owner:'u2', start:'2026-06-01', end:'2026-09-30',
    goals:'Zero non-conformity in Q3 regulatory inspection.',
    monitoring:'Bi-weekly EHS steering committee.',
    easeCost:'', watchlist:['u1'], actionIds:[], done:0, total:0, module:'EHS' },
];

// Alerts — lightweight, action-less items surfaced in the Kanban.
// They only carry a short instruction; tapping one will redirect to its source record.
const AM_ALERTS = [
  { id:'AL-3456', kind:'alert', label:'Review TAG n°3456',                 status:'Open',        pillar:'reliability', source:'TAG+',   due:'2026-06-04', structure:'Fabrication > Line 4 > Conveyor A' },
  { id:'AL-3478', kind:'alert', label:'Validate SMAT walkthrough n°412',   status:'Open',        pillar:'safety',      source:'SMAT',   due:'2026-06-02', structure:'EHS > Production Floor' },
  { id:'AL-3502', kind:'alert', label:'Acknowledge event n°0231',          status:'In Progress', pillar:'safety',      source:'eEvent', due:'2026-05-29', structure:'EHS > Zone C3' },
  { id:'AL-3519', kind:'alert', label:'Approve risk assessment n°0078',    status:'Open',        pillar:'risk',        source:'EHS',    due:'2026-06-08', structure:'Quality > QC Lab' },
  { id:'AL-3530', kind:'alert', label:'Confirm eCheck reading n°1190',     status:'In Progress', pillar:'risk',        source:'eCheck', due:'2026-06-01', structure:'Production > Unit 7 > Instrumentation' },
];

const AM_CURRENT_USER = { id:'u1', name:'Jean Dupont', initials:'JD', role:'Manager', site:'FR-Lyon — Fabrication Plant', color:'#3382C4' };

const AM_NOTIFS = [
  { id:'n1', type:'overdue',  icon:'🔴', title:'ACT-2026-00141 overdue',         body:'EHS risk register not updated — 12 days past due.',           time:'2h ago',  read:false },
  { id:'n2', type:'assigned', icon:'📋', title:'New action assigned to you',      body:'ACT-2026-00142 — conveyor belt inspection assigned.',          time:'5h ago',  read:false },
  { id:'n3', type:'comment',  icon:'💬', title:'Comment on ACT-2026-00140',      body:'Sofia: "Two operators trained. Last session May 29."',          time:'1d ago',  read:true  },
  { id:'n4', type:'status',   icon:'✅', title:'ACT-2026-00138 completed',        body:'Quality check procedure doc validated by Jean Dupont.',        time:'2d ago',  read:true  },
  { id:'n5', type:'created',  icon:'➕', title:'New action in your pillar',       body:'ACT-2026-00134 — Emergency evacuation plan review.',           time:'3d ago',  read:true  },
];

Object.assign(window, {
  AM_CATEGORIES, AM_STATUS_CFG, AM_PRIORITY_CFG, AM_SOURCE_CFG,
  AM_USERS, AM_ACTIONS_INIT, AM_PLANS_INIT, AM_CURRENT_USER, AM_NOTIFS, AM_ALERTS,
});
